# Generated by Django 2.1.7 on 2019-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('work', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
