# Generated by Django 2.1.7 on 2019-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190214_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='countmark',
            field=models.IntegerField(default='0', editable=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mark',
            field=models.DecimalField(decimal_places=1, default='-1', max_digits=3),
        ),
    ]
