# Generated by Django 2.1.7 on 2019-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190221_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mark',
            field=models.IntegerField(default='0'),
        ),
    ]
