# Generated by Django 2.1.7 on 2019-02-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190221_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.IntegerField()),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Restaurant'),
        ),
    ]
