# Generated by Django 2.1.7 on 2019-02-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190221_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_restaurant',
            new_name='restaurant',
        ),
    ]
