# Generated by Django 2.1.7 on 2019-02-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190221_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
