# Generated by Django 2.1.7 on 2019-02-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
