# Generated by Django 2.1.4 on 2019-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190404_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('CAFE', 'Кафе'), ('REST', 'Ресторан')], default='REST', max_length=2),
        ),
    ]
