# Generated by Django 2.1.4 on 2019-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('CF', 'Кафе'), ('RS', 'Ресторан')], default='RS', max_length=2),
        ),
    ]
