# Generated by Django 2.1.4 on 2019-04-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_restaurant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='4')),
                ('smoke', models.BooleanField()),
                ('window', models.BooleanField()),
                ('reservation', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('CF', 'Кафе'), ('RS', 'Ресторан'), ('BR', 'Бар')], default='RS', max_length=2),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant'),
        ),
    ]
