# Generated by Django 2.1.4 on 2019-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190411_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
