# Generated by Django 2.1.4 on 2019-04-15 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_auto_20190411_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reservation', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('CF', 'Кафе'), ('RS', 'Ресторан'), ('BR', 'Бар'), ('PC', 'Пиццерия'), ('KR', 'Караоке'), ('BG', 'Бургерная')], default='RS', max_length=2),
        ),
        migrations.AddField(
            model_name='timetable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Table'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
