# Generated by Django 2.1.4 on 2019-04-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20190415_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(default='Выходной', max_length=15)),
                ('tuesday', models.CharField(default='Выходной', max_length=15)),
                ('wednesday', models.CharField(default='Выходной', max_length=15)),
                ('thursday', models.CharField(default='Выходной', max_length=15)),
                ('friday', models.CharField(default='Выходной', max_length=15)),
                ('saturday', models.CharField(default='Выходной', max_length=15)),
                ('sunday', models.CharField(default='Выходной', max_length=15)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant')),
            ],
            options={
                'db_table': 'Week',
            },
        ),
    ]
