# Generated by Django 2.1.7 on 2019-04-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20190424_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='end',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start',
        ),
        migrations.AddField(
            model_name='timetable',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='friday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='saturday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='sunday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday',
            field=models.CharField(default='Выходной 0', max_length=15),
        ),
    ]
